### DISCUSSION TITLE
Trix field does not support dark mode in Nova 4

### DISCUSSION THREAD

**Discussion by amanpatel** [laravel/nova-issues#3955] [Ideas & Feature Requests]
- Laravel Version: v8.83.7
- Nova Version: 4.0.5
- PHP Version: 8.0.9
- Database Driver & Version: postgres 11
- Operating System and Version: macOS (latest stable)
- Browser type and version: Chrome (latest stable)
- Reproduction Repository: https://github.com/###/###

### Description:
Great work on the Nova 4 release! :-)

Nova 4 introduces the awesome dark mode. However we just found that the Trix editor does not display in the best way possible for darkmode. See screenshot.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add any Trix field to a nova 4 installation with dark mode enabled.

<img width="1200" alt="Screen Shot 2022-04-07 at 9 28 54 AM" src="https://user-images.githubusercontent.com/226976/162222873-277fe40c-39f7-4bca-98cf-97539e93e5b1.png">

### Possible solution
Since Trix ships with `background-image css svg` icons. Its not possible to modify the color easily. However a possible "acceptable" solution could be to just let the tool bar not be in darkmode:

```
.trix-toolbar .trix-button {
  background: #ddd !important; /* force the background to be a light color since Trix icons do not support dark mode */
}
```

The text box itself looks different but definitely acceptable in my opinion. Bonus if it would look the same as the rest of nova `<textarea>` styling.

**Comment by davidhemphill** [comment]
Trix doesn't currently support dark mode: https://github.com/basecamp/trix/issues/947

We will update the field once it does.

**Reply by mrleblanc101** [reply]
Just wondering, why is this a conversation and not an open issue ?
Trix hasn't been updated in almost 2 years. And there hasn't been any commit in almost a year.

**Comment by stanislav-cervenak** [comment]
If someone wanted at least such an adjustment so that it could be viewed

```css
html.dark {
    .trix-button-row {
        .trix-button-group {
            border-color: #0f172a;

            .trix-button {
                background-color: #94a3b8;
                border-color: #0f172a;

                &.trix-active {
                    background-color: lighten(#94a3b8, 10%);
                }
            }
        }
    }

    .trix-content {
        background-color: #0f172a;
        border-color: #344155;
    }
}
```

![Snímka obrazovky 2022-06-15 o 20 16 14](https://user-images.githubusercontent.com/6931349/173896905-af017471-89c2-4115-9826-78fe4b0c73ce.png)
