### DISCUSSION TITLE
How to change sidebar colours easily?

### DISCUSSION THREAD

**Discussion by ziming** [laravel/nova-issues#4244] [Q&A]
After upgrading to v4. my client complained that he hates the colour of the v4 nav left sidebar as it's the same colour as the right content side now, unlike v3. what's an easy way to change it? Can a setting be added to make this easier?

**Comment by bashgeek** [comment]
Create an asset:
`php artisan nova:asset myself/sidebarcolor`

Edit the assets CSS with (put in the colors you want for light and dark mode respectively):
```css
html:not(.dark) [data-testid="content"] > div:nth-of-type(1) { background: #ccc; }
html.dark [data-testid="content"] > div:nth-of-type(1) { background: #000; }
```

And compile.

If you want the sidebar to fill the whole window height you can put in an additional min-height:
```css
html:not(.dark) [data-testid="content"] > div:nth-of-type(1) { background: #ccc; min-height: 100%; }
html.dark [data-testid="content"] > div:nth-of-type(1) { background: #000; min-height: 100%; }
```
