### DISCUSSION TITLE
Sticky sidebar

### DISCUSSION THREAD

**Discussion by schonhoff** [laravel/nova-issues#5378] [Q&A]
Hey!

Is there a way to get the sidebar to be sticky? If I scroll a large resource (5-10 relationship fields) I need to scroll back to the top for the navigation. That can be frustrating for my customers. Can anyone help me?

**Comment by schonhoff** [comment]
Maybe this is a feature request or has somebody get this to work?

**Comment by dishant-hupp** [comment]
I don’t have a ready-made solution yet, but I’ve run into the same issue before. There’s a package called **[Nova Fixed Bars](https://github.com/cloudcake/nova-fixed-bars)** that might help; however, it’s quite old, so I’m not sure how reliable it is with the current Nova versions.

In my case, I was able to achieve the desired behavior using the following CSS:

```css
/* Target the 2nd child div of the element with dusk="content" inside #nova */
#nova > [dusk="content"] > div:nth-child(2) {
    max-height: calc(100vh - 56px);
    overflow: auto;
}
```
