### DISCUSSION TITLE
Markdown field `withMeta` has no effect

### DISCUSSION THREAD

**Discussion by kichetof** [laravel/nova-issues#6858] [Ideas & Feature Requests]
- Laravel Version: 12.14.1
- Nova Version: 5.7.1
- PHP Version: 8.4.6

### Description:

As `Markdown` field extends `Field` who extends `FieldElement` and `Element`, we have access to `withMeta` method. (this applicable for other fields too). But, nothing happens with our meta.

My use case, I've some Markdown presets and I want to apply css style. Actually, I can apply like that:

```css
.prose {
    text-align: justify;
    font-size: var(--text-lg);
    line-height: var(--tw-leading, var(--text-lg--line-height))
}
```

But, `prose` class is applied on textarea too and I can't apply different style.

If I can set something like that:

```php
->withMeta([
    'extraAttributes' => ['aria-preset' => 'custom']
])
```

I would be able to set a custom style to it.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Apply whatever on withMeta has no effect.
```php
Markdown::make('Content body', 'body')
    ->preset('custom', CustomMarkdownPreset::class)
    ->withMeta([
        'extraAttributes' => ['aria-preset' => 'custom'],
    ]),
```

Many thanks!
