### ISSUE TITLE
Scrollbar appears behind chart in partition metric

### ISSUE THREAD

**Issue by xorspark** [laravel/nova-issues#1510]
- Laravel Version: 5.8.1.0
- Nova Version: 2.0.1
- PHP Version: 7.3.1
- Operating System and Version: Windows 10 
- Browser type and version: Firefox, Chrome, Edge (latest versions as of 4/10)

### Description:
This issue has been previously reported in #93, #217, and #925 but the issue is still occurring as of Nova 2.0.1. If a partition metric has enough items to trigger a scrollbar (more than five) a scrollbar will appear behind the chart as seen here:

![2019-04-10 09_11_40-Users By Status Scrollbar](https://user-images.githubusercontent.com/2679427/55883342-26fd9e00-5b74-11e9-8e1a-318ff7421d0b.png)

### Steps To Reproduce:
Same as the previous issue:
1. Create a partition metric as described in the docs (example php artisan nova:partition UsersPerPlan). 
2. Make sure there are more than 5 values for the metric.

**Comment by gpressutto5** [comment]
Same issue here... As a workaround, I've created a custom theme with `php artisan nova:theme` and added this css:

```css
.card-panel > .overflow-hidden.overflow-y-auto.max-h-90px {
  margin-right: 90px;
  /*max-height: 104px; use if the card title uses 1 line */
  max-height: 86px; /* use if the card title uses 2 lines */
}
```
