### ISSUE TITLE
Don't round image in resouce index

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1651]
![image](https://user-images.githubusercontent.com/38257723/58937618-9f9b6800-877b-11e9-8007-e7df2e46157a.png)

It is not very usefull and is meaningless. May be by default need not to round any images.

**Comment by bolechen** [comment]
rewrite the nova css like this

```css
table.w-full td img {
    border-radius: 0;
}
```
