### ISSUE TITLE
Allow customisation of Code Field's CodeMirror's options for performance issues

### ISSUE THREAD

**Issue by olivM** [laravel/nova-issues#1783]
the current default behaviour of CodeMirror is : viewportMargin: Infinity + height:auto with no scrolling

but this has a huge impact on performance when loading long/complex code
( https://codemirror.net/doc/manual.html#option_viewportMargin : 

> Can be set to Infinity to make sure the whole document is always rendered, and thus the browser's text search works on it. This will have bad effects on performance of big documents.  )

So it's should be nice to be able to fix the code editor max-height and allow scrolling + limit viewportMargin to N

**Comment by jbrooksuk** [comment]
In Nova v2.0.9 the `viewportMargin` is now set to `Infinity`.

**Comment by jbrooksuk** [comment]
Sorry, I think I may have misread what you were saying. `viewportMargin: Infinity` is currently set, but then there is a `.CodeMirror-scroll` class which has `height: auto` and `overflow: visible` properties set which is causing the performance issues?

**Comment by olivM** [comment]
yes the `viewportMargin: Infinity` tells CodeMirror to render everyline of the content even if it's not visible. that's a performance issue

and the `height: auto` allow the editor to grow to display the whole content

so the code field is not usable with big content ( like a big geoJSON in my case )

( i'm working on a custom-field to address this issues )

**Comment by jbrooksuk** [comment]
I see. We should limit the `viewportMargin` to something smaller and remove `height: auto`.

**Comment by jbrooksuk** [comment]
Instead, setting `max-height` maybe?

**Comment by olivM** [comment]
just the max-height wont able to scroll the editor content.
i usually put this css to override CodeMirror styles : 

```css
.CodeMirror {
    max-height: 600px  !important;
    margin: auto  !important;
    position: unset !important;
    z-index: unset !important;
    height: 600px  !important;
}

.CodeMirror-scroll {
    height: 100%  !important;
    overflow: auto !important;
    box-sizing: unset  !important;
}
```
