### ISSUE TITLE
accessibility color blindness - with quickfix

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#1823]
People with color blindness can not distinguish the color of the boolean dot.

Quickfix:

With adding following CSS snippet

```css        
.inline-block.rounded-full.bg-danger {
    height: 0px;
}
.inline-block.rounded-full.bg-danger:before {
    content:"\00d7";
    color: var(--danger);
    font-weight: bold;
    font-size: 125%;
    margin-top: -7px !important;
}
.inline-block.rounded-full.bg-success {
    height: 0px;
}
.inline-block.rounded-full.bg-success:before {
    content:  "\2713";
    color: var(--success);
    font-weight: bold;
}
```
 into a style section on

`/resources/views/vendor/nova/layout.blade.php`

will transform the dots into icons:

![campaigns 2019-08-15 08-44-13](https://user-images.githubusercontent.com/158588/63077741-9ed04080-bf39-11e9-9d0d-3ae4780fce3b.png)
