### ISSUE TITLE
PAGE EXPIRED (Vapor deployment issue)

### ISSUE THREAD

**Issue by u12206050** [laravel/nova-issues#3099]
- Laravel Version: 8.0.0
- Nova Version: 3.13.0
- PHP Version: 7.4.0
- Database Driver & Version: mysql 8.21
- Operating System and Version: VAPOR
- Browser type and version: Chrome

### Description:

Deployed nova site using vapor. Trying to login I simply get PAGE EXPIRED on successful login.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Deploy using VAPOR with following config:

 ```
id: #####
name: my-project
separate-vendor: true
environments:
    production:
        database: my-project-db
        capacity: 5
        memory: 512
        cli-memory: 512
        runtime: php-7.4
        layers:
          - vapor:php-7.4
          - vapor:php-7.4:imagick
        build:
            - 'COMPOSER_MIRROR_PATH_REPOS=1 composer install --no-dev'
            - 'php artisan event:cache'
            - 'npm ci && npm run prod && rm -rf node_modules'
    staging:
        database: my-project-db
        memory: 512
        cli-memory: 512
        runtime: php-7.4
        layers:
          - vapor:php-7.4
          - vapor:php-7.4:imagick
        build:
            - 'COMPOSER_MIRROR_PATH_REPOS=1 composer install'
            - 'php artisan event:cache'
            - 'npm ci && npm run dev && rm -rf node_modules'
```
