### ISSUE TITLE
default font-family

### ISSUE THREAD

**Issue by dokimastikos** [laravel/nova-issues#414]
The font does not support Greek characters and the result is ugly. There must be an easy way to change it.

<img width="499" alt="greek" src="https://user-images.githubusercontent.com/16783065/44996025-5e88e400-afae-11e8-9bdc-93527ad6930d.png">

**Comment by bonzai** [comment]
You can change the default font family by creating a new CSS file and registering it with Nova.

### public/css/nova.css

```css
/* Random font from Google Fonts */
@import url('https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c');

.font-sans {
    font-family: 'M PLUS Rounded 1c', sans-serif;
}
```

### app/Providers/NovaServiceProvider.php

```php
public function boot()
{
    parent::boot();

    Nova::style('greek-font', asset('css/nova.css'));
}
```
