### ISSUE TITLE
Trix field CSS is overwritten by Nova

### ISSUE THREAD

**Issue by mrleblanc101** [laravel/nova-issues#4374]
- Laravel Version: 9.11.0
- Nova Version: 4.2.7
- PHP Version: 8.1.0

### Description:
`<ul>` and `<ol>` have `list-style: none;` applied to them inside Trix field which make it had to understand since they dont have bullet or number next to them.
![Capture d’écran, le 2022-06-06 à 16 32 45](https://user-images.githubusercontent.com/17392251/172243931-7762b274-d05c-40b2-8ac1-f27ed1d23eb1.png)
![Capture d’écran, le 2022-06-06 à 16 32 33](https://user-images.githubusercontent.com/17392251/172243949-83246906-9f6f-458b-b98f-08a14814818b.png)

**Comment by RobertBoes** [comment]
If anyone is running into this issue, I've solved it by loading a custom css file with `Nova::remoteStyle(mix('css/nova-fixes.css'));` containing the following css:
```css
.trix-content ol {
    list-style-type: decimal;
}
.trix-content ul {
    list-style-type: disc;
}
```
