### ISSUE TITLE
Conditional create/update/delete actions leads to inconsistent alignment of actions on index

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#4843]
- Laravel Version: 9.x
- Nova Version: 4.15.x

### Description:
If your policy for a resource makes the various actions only display under certain conditions the index row actions can seem a little disorganised:
![image](https://user-images.githubusercontent.com/20278756/192068050-a7f41427-3294-45c2-95d2-a1e239561078.png)

### Proposal
I propose adopting a grid style instead so that the above would display like this:
![image](https://user-images.githubusercontent.com/20278756/192068186-9895ba16-f0b9-4126-b3dc-7902be1e52d5.png)

### Alternative Proposal
Show disabled buttons instead of hiding them when not authorized

#### Container
**Before**
```html
<div class="flex items-center justify-end space-x-0 text-gray-400">
```
**After**
```html
<div class="grid grid-cols-4 gap-x-2 items-center space-x-0 text-gray-400">
```

#### Button
**Before**
```html
<a class="toolbar-button hover:text-primary-500 px-2">
```
**After**
```html
<a class="toolbar-button md:col-start-1 aspect-square hover:text-primary-500">
```

### Work around
<details>
<summary>
Click for CSS to make this work externally if not added to core
</summary>

```css
[data-testid="resource-table"] tbody tr td:last-child > div {
    display: grid;
    grid-template-columns: [actions] 1fr [view] 1fr [edit] 1fr [delete] 1fr;
    gap: 0 0.5rem;
}

[data-testid="resource-table"] tbody tr td:last-child > div > .toolbar-button {
    aspect-ratio:1;
    padding-left:0;
    padding-right:0;
}

[data-testid="resource-table"] tbody tr td:last-child > div > div:first-child {
    grid-column-start: actions;
}

[data-testid="resource-table"] tbody tr td:last-child > div > [aria-label="View"] {
    grid-column-start: view;
}

[data-testid="resource-table"] tbody tr td:last-child > div > [aria-label="Edit"], [data-testid="resource-table"] tbody tr td:last-child > div > [aria-label="Edit Attached"] {
    grid-column-start: edit;
}

[data-testid="resource-table"] tbody tr td:last-child > div > [aria-label="Delete"],
[data-testid="resource-table"] tbody tr td:last-child > div > [aria-label="Detach"],
[data-testid="resource-table"] tbody tr td:last-child > div > [aria-label="Restore"] {
    grid-column-start: delete;
}
```
</details>
