### ISSUE TITLE
IE11 Object Error "Unable to get property 'start' of undefined or null reference"

### ISSUE THREAD

**Issue by crumb1e** [laravel/nova-issues#822]
- Laravel Version: 5.7.8
- Nova Version: 1.1.4
- PHP Version: 7.1.20

### Description:
Nova is unusable on IE11.

After logging in nothing gets rendered and there are two console errors:

![screen shot 2018-10-09 at 13 26 17](https://user-images.githubusercontent.com/18497168/46669299-f178f780-cbc6-11e8-9a5b-5c39e984dd6d.png)

### Steps To Reproduce:
1. Open the Nova backend on IE11 with the console open and log in.

**Comment by bradenkeith** [comment]
There are 2 things that need to happen to allow Nova to display in IE11:

1. Remove destructuring from the `resources/views/vendor/partials/user.blade.php` partial
1. Install a polyfill for ES6 promises

I will detail how to do both here, as neither require changes to Nova core. Note, that the reliance on Tailwind still means coloration looks way off in IE11, and an IE stylesheet fallback would also be recommended, but not covered below:

1. There's million different ways you could go about this in order to overcome the destructuring issue. What I'm going to do here is to try to keep the existing functionality.

Destructuring is not supported in IE11 (without going through something like Babel). So`slot-scope="{toggle}"` directly in your blade template is not going to work. We need to extrapolate it to a Vue file of it's own so it can go through the compiling process.

Create `UserDropdown.vue` in your project. You'll see I'm importing the components directly from Nova, so all that functionality remains. I then created 2 slots I can access from my blade template.
```vue
<template>
    <dropdown>
        <dropdown-trigger class="h-9 flex items-center" slot-scope="{toggle}" :handle-click="toggle">
            <slot name="user-trigger"></slot>
        </dropdown-trigger>

        <dropdown-menu slot="menu" width="200" direction="rtl">
            <slot name="menu"></slot>
        </dropdown-menu>
    </dropdown>
</template>

<script>
    import dropdown from '../../../../vendor/laravel/nova/resources/js/components/Dropdown'
    import dropdownMenu from '../../../../vendor/laravel/nova/resources/js/components/DropdownMenu'
    import dropdownTrigger from '../../../../vendor/laravel/nova/resources/js/components/dropdownTrigger'
</script>
```

Create a nova.js file in your project
```js
Nova.booting((Vue, router) => {
    Vue.component('user-dropdown', require('./components/UserDropdown'));
})
```

Register this JS file in your NovaServiceProvider boot method
```php
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();
        Nova::script('CustomScript', __DIR__.'/../../public/js/nova.js');
    }
```

Update your `user.blade.php` template to use the new user-dropdown vue component
```php
<user-dropdown>
    <span slot="user-trigger" class="h-9 flex items-center">
        <img src="https://secure.gravatar.com/avatar/{{ md5(auth()->user()->email) }}?size=512" class="rounded-full w-8 h-8 mr-3"/>

        <span class="text-90">
            {{ auth()->user()->name }}
        </span>
    </span>
    <span slot="menu">
        <ul class="list-reset">
            <li>
                <a href="{{ route('nova.logout') }}" class="block no-underline text-90 hover:bg-30 p-3">
                    {{ __('Logout') }}
                </a>
            </li>
        </ul>
    </span>
</user-dropdown>
```
That's it! Nova will now give you a new error message about Promises being unsupported.

2. We need to polyfill Promises

I regularly use this polyfill, which has worked great - https://github.com/stefanpenner/es6-promise

All you need to do after adding it's dependency to your package, is to put it at the top of `nova.js` created in step 1:

```js
require('es6-promise/auto');
Nova.booting((Vue, router) => {
    Vue.component('user-dropdown', require('./components/UserDropdown'));
})
```

I'm sure this will be one of those posts I Google in a few months and find my own solution, so wanted to go ahead and document the work around for everyone!

**Comment by bradenkeith** [comment]
Here's a quick stylesheet to resolve some of the common stylings required for Nova in IE11. You can add this to your NovaServiceProvider boot method as well `Nova::style('CustomTheme', __DIR__.'/../../public/css/nova.css');`

```css
.bg-30, .hover\:bg-30:hover, .table th {
	background-color: #f4f7fa;
}
.bg-40, .hover\:bg-40:hover {
	background-color: #eef1f4;
}
.bg-logo, .bg-white, .card {
	background-color: #ffffff;
}
.btn-primary, .bg-primary {
	background-color: #4099de;
	color: #fff;
}
.btn-primary:hover{
	background-color: #297ec0;
}
.table tr:hover td {
	background-color: #f6fbff;
}
.form-select, .btn-white {
	background-color: #fff;
}

.text-black {
	color: #000;
}
.text-white {
	color: #fff;
}
.text-90 {
	color: #252d37;
}
.text-80 {
	color: #7c858e;
}
.text-70 {
	color: #b3b9bf;
}
.text-primary, .hover\:text-primary:hover {
	color: #4099de;
}
.table th {
	color: #7c858e;
}
.form-input-bordered {
	color: #bacad6;
}

.sidebar-icon path {
	fill: #b3c1d1;
}
.fill-60 {
	fill: #bacad6;
}
.fill-80 {
	fill: #7c858e;
}

.table td, .table th, .border-50 {
	border-color: #e3e7eb;
}
.form-input {
	border-color: #ffffff;
}
.form-input-bordered, .form-select {
	border-color: #bacad6;
}
.border-40 {
	border-color: #eef1f4;
}
```
