### ISSUE TITLE
Empty markdown field has tiny clickable area

### ISSUE THREAD

**Issue by dwyer14** [laravel/nova-issues#922]
- Laravel Version: 5.7.11
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
When creating a new resource with a markdown field  (or editing one that has no content in the field), the clickable area of the Markdown is really tiny, and doesn't match the visible outline of the input. The `div.CodeMirror` appears to be the clickable element, and (on my monitor, at least) it's about 8px wide:

![image](https://user-images.githubusercontent.com/13950848/47854004-8d54e800-ddae-11e8-94af-33fe7e6eca5f.png)

The easiest fix (which works well when I plug this into Chrome dev tools) is making it full-width:
```css
.CodeMirror {
    position: relative;
    overflow: hidden;
    background: #fff;
    width: 100%; /* Added. */
}
```

### Steps To Reproduce:
1. Create a resource with a markdown field.
2. Try clicking in the right 50% of the field, from the create form.
